[project]
name = "divvy-transport-analysis"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "dbt>=1.0.0.40.7",
    "dbt-databricks>=1.10.14",
]
